apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    name: mysql-pod
    app: wordpress
spec: 
  containers:
  - name: mysql-container
    image: mysql:8
    ports: 
    - containerPort: 3306
    env:
    - name: MYSQL_USER 
      value: "wp-user"  
    - name: MYSQL_PASSWORD
      value: "@Strongpassword@1234@"
    - name: MYSQL_DATABASE
      value: "wordpress"
    - name: MYSQL_ROOT_PASSWORD
      value: "chandu@1234"
