apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: wordpress-deployment
  labels:
    name: wordpress-deployment
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: wordpress
  template:
    metadata:
      name: wordpress-pod
      labels: 
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-service:3306"

        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: WORDPRESS_DB_NAME
      
        - name: WORDPRESS_DB_USER
          valueFrom: 
            secretKeyRef:
              name: wordpress-secrets
              key: WORDPRESS_DB_USER 
 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: WORDPRESS_DB_PASSWORD
