apiVersion: v1
kind: Pod
metadata: 
  name: worker-pod
  labels:
    name: worker-pod
    app: voting-application-app
spec:
  containers:
  - name: worker-container
    image: chandu22727/examplevotingapp_worker 
