apiVersion: v1
kind: Secret

metadata:
  name: icingadb-secrets

type: Opaque

stringData:
  ICINGADB_DATABASE_HOST: mysql-icinga-service
  ICINGADB_DATABASE_PORT: "3306"

#  ICINGADB_DATABASE_USER: icingadb
#  ICINGADB_DATABASE_PASSWORD: @Strongpassword@1234@

  ICINGADB_REDIS_HOST: redis-service
  ICINGADB_REDIS_PORT: "6379"
