apiVersion: v1
kind: Secret

metadata:
  name: icingaweb2-secrets

type: Opaque
stringData:
  ICINGAWEB2_DATABASE_HOST: mysql-icinga-service
  ICINGAWEB2_DATABASE_PORT: "3306"

  ICINGAWEB2_DATABASE_USER: icingaweb2
#  ICINGAWEB2_DATABASE_PASSWORD: @Strongpassword@1234@

  ICINGADBWEB2_DATABASE_NAME: icingaweb2
