apiVersion: v1
kind: Secret
metadata:
  name: mysql-icinga-secrets
type: Opaque

stringData:
#  MYSQL_ROOT_PASSWORD: chandu@1234
  MYSQL_DATABASE: icingadb
  MYSQL_USER: icingadb
#  MARIADB_ROOT_PASSWORD: @Strongpassword@1234@
