apiVersion: v1
kind: ConfigMap

metadata:
  name: icingadb-config

data:
  config.yml: |
    database:
      type: mysql
      host: mysql-icinga-service
      port: 3306
      database: icingadb
      user: icingadb
      password: "@Strongpassword@1234@"

    redis:
      host: redis-service
      port: 6379
