apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # - alertmanager:9093

    rule_files:
      - "first_rules.yml"

    scrape_configs:

      - job_name: "prometheus"

        static_configs:
          - targets: ["localhost:9090"]
            labels:
              app: "prometheus"

      - job_name: "node"
        static_configs:
          - targets: # ["172.18.0.2:9100"]
              - 172.18.0.2:9100
        # kubernetes_sd_configs:
       #   - role: endpoints
       # relabel_configs:
       #   - source_labels: [__meta_kubernetes_service_name]
       #     action: keep
       #     regex: node-exporter-service
      - job_name: "blackbox"

        metrics_path: /probe

        params:
          module: [http_2xx]

        static_configs:
          - targets:  ["http://172.18.0.2:30009/"]
             # - http://172.18.0.2:30009/
            labels:
              app: "prometheus"

        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target

          - source_labels: [__param_target]
            target_label: instance

          - target_label: __address__
            replacement: blackbox-service:9115
